name: Generate Horror Series and Send to Telegram

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight UTC
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: horror-series
  cancel-in-progress: true

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng libsndfile1

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers llama-cpp-python huggingface_hub kokoro soundfile requests

      # Create directory for outputs
      - name: Create output directory
        run: mkdir -p outputs

      # Run the horror generator script
      - name: Run horror generator
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python horror_generator.py

      # Upload artifacts
      - name: Upload story and audio
        uses: actions/upload-artifact@v4
        with:
          name: horror-series-outputs
          path: outputs/

      # Clean up
      - name: Clean up
        run: |
          rm -rf outputs
          rm -f fast_outline.md